name: Exp2Ipynb
channels:
- conda-forge
dependencies:
- pip=20.3.3
- ipykernel
- jupyterlab
- python=3.9
- matplotlib=3.1.3
- numpy=1.18.1
- joblib=0.14.1
- pandas=1.0.3
- scipy=1.4.1
- pylab-sdk=1.1.2
- openpyxl=3.0.3
- scikit-learn>=0.24.2
- logomaker>=0.8
- deap>=1.3.1
- pydot>=1.4.1

